name: Deploy to EC2 with Nginx

on:
  push:
    branches:
      - main  # Runs on push to the 'main' branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Update and install Nginx
          sudo apt update && sudo apt install -y nginx git

          # Clone the repository
          sudo rm -rf /var/www/html/*
          sudo git clone https://github.com/jasonsanjay21/DevOpsPF.git /var/www/html

          # Restart Nginx
          sudo systemctl restart nginx
          EOF
